Removed unused lines. Removed Spring Security dependency and WebSecur…
endava-pad-backend-microservices/gateway pull request #11
Opened 2019-06-19 18:42 UTC by ayancovich

…ity Bean

2019-06-19 20:32 UTC, nestorreloaded requested changes

2019-06-19 20:32 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PostFilter.java
> +		logger.log(Level.INFO,"Calling audit on PostFilter...");
Please remove this logger line

2019-06-19 20:32 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PreFilter.java
> +		logger.log(Level.INFO,"Checking token on PreFilter...");
Please remove this logger line if not used

2019-06-20 14:26 UTC, nestorreloaded commented
Please fix codacy warnings, we have unused imports in the code, as described here:
https://app.codacy.com/app/Microservices/gateway/pullRequest?prid=3742762

2019-06-21 17:29 UTC, exe135 approved these changes

2019-06-21 17:31 UTC, nestorreloaded approved these changes

2019-07-01 12:56 UTC, merged