Added audit ms to Postfilter
endava-pad-backend-microservices/gateway pull request #9
Opened 2019-06-07 20:00 UTC by ayancovich

2019-06-07 20:11 UTC, nestorreloaded requested changes
Please see the notes

2019-06-07 20:11 UTC, nestorreloaded commented on src/main/java/com/endava/controller/RefreshController.java
> +						String.valueOf(i.getPort()), "/actuator/refresh");
This should be a constant

2019-06-07 20:11 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PostFilter.java
>  		return null;
Please don't return null

2019-06-07 20:11 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PostFilter.java
> +				// logger.warn("Error reading body", e);
We should do something in the exception, at least log the error

2019-06-07 20:11 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PostFilter.java
> +				response_body = CharStreams.toString(new InputStreamReader(responseDataStream, "UTF-8"));
Use constants

2019-06-07 20:11 UTC, nestorreloaded commented on src/main/java/com/endava/filters/PreFilter.java
> +			data.put("token", token);
Use constants

2019-06-07 20:14 UTC, ayancovich commented on src/main/java/com/endava/controller/RefreshController.java
> +						String.valueOf(i.getPort()), "/actuator/refresh");
Done

2019-06-10 13:21 UTC, nestorreloaded approved these changes

2019-06-10 13:22 UTC, exe135 approved these changes

2019-06-10 13:22 UTC, merged